version: "3.5"

networks:
  cassandra-net:
    driver: bridge 

services:
  cassandra1:
    image: cassandra:latest
    ports:
      - 7000:7000
      - 9042:9042
    container_name: "cassandra-1"
    networks:
      cassandra-net:
    volumes:
      - cassandra1-data:/var/lib/cassandra
    environment:
      - CASSANDRA_START_RPC=true       # default
      - CASSANDRA_RPC_ADDRESS=0.0.0.0  # default
      - CASSANDRA_LISTEN_ADDRESS=auto  # default, use IP addr of container # = CASSANDRA_BROADCAST_ADDRESS
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=my-datacenter-1
    restart:
      on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3
    
volumes:
  cassandra1-data:
