version: "3.5"

services:
  cassandradb:
    image: cassandra:3.11 # Use the official Cassandra image from Docker Hub
    container_name: cassandra-container
    ports:
      - "9042:9042" # Expose Cassandra's default port
    volumes:
      - ./cassandra_data:/var/lib/cassandra # Persist Cassandra data outside the container
    environment:
      - MAX_HEAP_SIZE=512M # Optional: set Cassandra heap size
      - HEAP_NEWSIZE=100M  # Optional: set Cassandra new generation heap size
    networks:
      - cassandra_network
  cassandradb2:
    image: cassandra:3.11 # Use the official Cassandra image from Docker Hub
    container_name: cassandra-container2
    volumes:
      - ./cassandra_data2:/var/lib/cassandra # Persist Cassandra data outside the container
    environment:
      - MAX_HEAP_SIZE=512M # Optional: set Cassandra heap size
      - HEAP_NEWSIZE=100M  # Optional: set Cassandra new generation heap size
      - CASSANDRA_SEEDS=cassandra-container
    networks:
      - cassandra_network

networks:
  cassandra_network:
    driver: bridge