spring:
    application:
        name: my_blockchain
    cassandra:
        keyspace-name: transportation_blockchain
        port: 9042
        contact-points: 127.0.0.1 #172.17.0.2
        local-datacenter: datacenter1

server:
    port: 8081