spring:
    application:
        name: my_blockchain
    cassandra:
        keyspace-name: transportation_blockchain
        port: 9042
        contact-points: localhost
        local-datacenter: datacenter1
        schema-action: none
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USER:guest}
        password: ${RABBITMQ_PASS:guest}

rabbitmq:
    create-wallet-queue: ${CREATE_WALLET_QUEUE:"create-wallet-queue"}
    create-transaction-queue: ${CREATE_TRANSACTION_QUEUE:"create-transaction-queue"}
server:
    port: 8081